package com.school.project.testing.dao;

import static org.junit.Assert.assertEquals;

import java.util.List;

import org.junit.FixMethodOrder;
import org.junit.Test;
import org.junit.runners.MethodSorters;

import com.school.project.dao.TicketDAO;
import com.school.project.model.Ticket;

@FixMethodOrder(MethodSorters.NAME_ASCENDING)
public class TestTicketDAO {

	@Test
	public void testGetTicketIsNull() {
		List<Ticket> tickets = TicketDAO.getInstance().getAll();
		for(int i = 0; i < tickets.size(); i++){
			Ticket result = TicketDAO.getInstance().get(i);
			assertEquals(null, result);
		}
	}
	@Test
	public void testAddTicket(){
		Ticket dummyTicket = new Ticket(1, "test_Ticket", "this ticket was generated by a unit test", 666.0, 1, false, false);
		TicketDAO.getInstance().add(dummyTicket);
		List<Ticket> tickets = TicketDAO.getInstance().getAll();
		Ticket result = tickets.get(tickets.size() - 1);
		System.out.println("Added " + result);
	}
	@Test
	public void testDeleteTicket(){
		Ticket dummyTicket = new Ticket(1, "test_Ticket Mk.2", "congratulations, your ticket evolved", 777.0, 1, false, false);
		TicketDAO.getInstance().add(dummyTicket);
		List<Ticket> tickets = TicketDAO.getInstance().getAll();
		Ticket result = tickets.get(tickets.size() - 1);
		TicketDAO.getInstance().delete(dummyTicket);
		System.out.println("Deleted " + result);
	}
	@Test
	public void testUpdateTicket(){
		List<Ticket> tickets = TicketDAO.getInstance().getAll();
		Ticket lastTicket = tickets.get(tickets.size() - 1);
		Ticket uDummyTicket = new Ticket(lastTicket.getId(), "test_Case Ticket", "this ticket was generated by a unit test", 666.0, 1, true, false);
		TicketDAO.getInstance().update(uDummyTicket);
		System.out.println("Updated Ticket with ID: " + lastTicket.getId());
	}	
}
